author: 吴建涛
description: 吴建涛(Leolord)，一个前端工程师，目前就职于北京字节跳动网络技术有限公司。这里是一些乱七八糟的东西。
google_analytics: UA-108823943-1
lang: cmn-Hans
logo: /assets/favicon-32x32.png
show_downloads: false
timezone: Asia/Shanghai
title: Leolord的博客
url: https://www.leolord.com
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: true
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "_site"]

twitter:
  username: LuckFatBoy

social:
  name: Leolord
  links:
    - http://weibo.com/p/1005051627615060
    - https://twitter.com/LucyFatBoy
    - https://www.facebook.com/profile.php?id=100003660305981

plugins:
  - jekyll-feed

collections:
  - 前端
  - 健身
  - 杂谈
  - 其他技术
